### ISSUE TITLE
Error: listen EADDRINUSE: address already in use /tmp/unix.sock

### ISSUE THREAD

**Issue by vickyisly** [theanarkh/nodejs-ipc#1]
使用测试case：
node test/testIpc/server.js 
node test/testIpc/client.js 
使用ctrl+c 终止node。 
再次运行上面两个测试case 报错：

➜  nodejs-ipc-main node test/testIpc/server.js 
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use /tmp/unix.sock
    at Server.setupListenHandle [as _listen2] (net.js:1300:21)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1462:5)
    at new Server (/Users/vicky/Downloads/nodejs-ipc-main/src/ipc/server.js:27:10)
    at Object.<anonymous> (/Users/vicky/Downloads/nodejs-ipc-main/test/testIpc/server.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '/tmp/unix.sock',
  port: -1
}

是哪里操作不当吗？ 这个unix的套接字被占用了不能释放？

**Comment by theanarkh** [comment]
可以先手动删除这个文件，中午我处理一下。

**Comment by theanarkh** [comment]
已fix，谢谢反馈

**Comment by vickyisly** [comment]
可以了，谢谢大佬
